apiVersion: v1
kind: Pod
metadata:
  name: secure-nginx
spec:
  initContainers:
    - name: decrypt-init
      image: localhost:5000/decrypt-init
      imagePullPolicy: Always
      securityContext:
        privileged: true
      command: ["/bin/bash", "-c"]
      args:
        - |
          echo "[*] Starting init container...";
          curl -o /tmp/decrypt.sh http://172.31.46.214:8080/decrypt.sh;
          chmod +x /tmp/decrypt.sh;
          /tmp/decrypt.sh;
      volumeMounts:
        - name: containerd-sock
          mountPath: /run/k3s/containerd/containerd.sock
  containers:
    - name: nginx
      image:  nginx-decrypted:latest 
      imagePullPolicy: Never
      ports:
        - containerPort: 80
  volumes:
    - name: containerd-sock
      hostPath:
        path: /run/k3s/containerd/containerd.sock
  restartPolicy: Never


